//get all post
### Request
GET http://localhost:8000/api/posts

### Request // filter posts with pages and limit
GET http://localhost:8000/api/posts?page=1&limit=2

### Request // order posts asc or desc
GET http://localhost:8000/api/posts?order=desc

### Request // filter posts with pages and limit && order posts asc or desc
GET http://localhost:8000/api/posts?page=1&limit=3&order=asc

### //get post by id
GET http://localhost:8000/api/posts/3

### //create post
POST http://localhost:8000/api/posts
Content-Type: application/json

{
    "post_title": "THIS IS new post",
    "post_content": "CLICK ME",
    "author_id": 6
}

### //update post
PUT http://localhost:8000/api/posts/5
Content-Type: application/json

{
    "post_title": "update for post -5-",
    "post_content": "Update for this post and confirmation",
    "author_id": 1
}

### //delete post
DELETE http://localhost:8000/api/posts/9

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

### //get user
GET http://localhost:8000/api/users/profile/4

### //register user
POST http://localhost:8000/api/users/register
content-Type: application/json

{
    "Username": "user510",
    "Email" : "te1s34t@gmaildsdfsdf5.com",
    "password" : "k1evin50"
}
### //login user

POST http://localhost:8000/api/users/auth/login
content-Type: application/json

{
    "Username": "user5",
    "password" : "k1evin5"
}
### //update user
PUT http://localhost:8000/api/users/profile/6
content-Type: application/json

{
    "Username": "testuser5",
      "Email" : "changedthis@gmail.com"  
}

### //update user
DELETE http://localhost:8000/api/users/profile/5



